services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: your user
      POSTGRES_PASSWORD: your password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
